# Generated by Django 5.0.4 on 2026-03-06 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('1CP', '1CP'), ('2CP', '2CP'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=5)),
                ('semester', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2')], max_length=2)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'level', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('COUR', 'Cours'), ('TD', 'TD'), ('TP', 'TP'), ('EXAM', 'Exam'), ('INTERRO', 'Interro'), ('OTHER', 'Other')], max_length=10)),
                ('academic_year', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='temp_uploads/')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('drive_id', models.CharField(blank=True, max_length=255, null=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='froms.module')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
